//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MssBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contratos()
        {
            this.Anexos = new HashSet<Anexos>();
        }
    
        public int Contrato_Id { get; set; }
        public Nullable<int> Documento_Id { get; set; }
        public Nullable<int> Isapre_Id { get; set; }
        public Nullable<int> Afp_Id { get; set; }
        public Nullable<int> CentroCosto_Id { get; set; }
        public Nullable<int> EstructuraSueldo_Id { get; set; }
        public string TipoContrato { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public string SegundoParrafo { get; set; }
        public string Instalacion { get; set; }
        public Nullable<double> Anticipacion { get; set; }
    
        public virtual Afp Afp { get; set; }
        public virtual CentrosDeCostos CentrosDeCostos { get; set; }
        public virtual Documentos Documentos { get; set; }
        public virtual EstructuraSueldos EstructuraSueldos { get; set; }
        public virtual Isapres Isapres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anexos> Anexos { get; set; }
    }
}
