//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MssBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documentos()
        {
            this.Contratos = new HashSet<Contratos>();
            this.Log_Documentos = new HashSet<Log_Documentos>();
        }
    
        public int Documento_Id { get; set; }
        public int DocumentoTipo_Id { get; set; }
        public int Usuario_Id { get; set; }
        public int Personal_Id { get; set; }
        public bool PorVisar { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string RutaFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contratos> Contratos { get; set; }
        public virtual Personal Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log_Documentos> Log_Documentos { get; set; }
    }
}
