//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MssBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finiquito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Finiquito()
        {
            this.Remuneraciones = new HashSet<Remuneraciones>();
        }
    
        public int Finiquito_Id { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> Articulo_Numero { get; set; }
        public string Comentario { get; set; }
        public Nullable<double> Vacaciones { get; set; }
        public Nullable<int> Documento_Id { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public string RutaFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remuneraciones> Remuneraciones { get; set; }
    }
}
