//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MssBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Log_Id { get; set; }
        public int Usuario_Id { get; set; }
        public string Accion { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
