//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MssBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Documentos = new HashSet<Documentos>();
        }
    
        public int Rut { get; set; }
        public string Dv { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Pais_Codigo { get; set; }
        public Nullable<int> Region_Codigo { get; set; }
        public Nullable<int> Provincia_Codigo { get; set; }
        public Nullable<int> Comuna_Codigo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string TelFijo { get; set; }
        public string TelCelular { get; set; }
        public string NombreContacto { get; set; }
        public string Parentesco { get; set; }
        public string TelContactoFijo { get; set; }
        public string TelContactoCelular { get; set; }
        public string TipoContrato { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string CursoOS10 { get; set; }
        public string Credencial { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> Calzado { get; set; }
        public string Pantalon { get; set; }
        public string Polera { get; set; }
        public string Polar { get; set; }
        public string Casaca { get; set; }
        public string Corbata { get; set; }
        public string Gorro { get; set; }
        public string Cazadora { get; set; }
        public string Camisa { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<int> CentroCosto_Id { get; set; }
        public Nullable<int> Usuario_Id { get; set; }
        public string Estado { get; set; }
        public Nullable<int> EstructuraSueldo_Id { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> Isapre_Id { get; set; }
        public Nullable<int> Afp_Id { get; set; }
        public Nullable<bool> Vigencia { get; set; }
        public Nullable<int> Id_Banco { get; set; }
        public string TipoCuenta { get; set; }
        public string NumeroCuenta { get; set; }
        public string Cargo { get; set; }
    
        public virtual Afp Afp { get; set; }
        public virtual Bancos Bancos { get; set; }
        public virtual CentrosDeCostos CentrosDeCostos { get; set; }
        public virtual Comunas Comunas { get; set; }
        public virtual EstructuraSueldos EstructuraSueldos { get; set; }
        public virtual Isapres Isapres { get; set; }
        public virtual Paises Paises { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual Regiones Regiones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos> Documentos { get; set; }
    }
}
