//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MssBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DOC_Contratos
    {
        public Nullable<int> DocumentoTipo_Id { get; set; }
        public Nullable<int> Personal_Id { get; set; }
        public Nullable<int> Usuario_Id { get; set; }
        public Nullable<bool> PorVisar { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string RutaFinal { get; set; }
        public Nullable<int> Contrato_Id { get; set; }
        public Nullable<int> CentroCosto_Id { get; set; }
        public Nullable<int> Isapre_Id { get; set; }
        public Nullable<int> Afp_Id { get; set; }
        public Nullable<int> EstructuraSueldo_Id { get; set; }
        public string TipoContrato { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> SueldoBase { get; set; }
        public Nullable<double> Gratificacion { get; set; }
        public Nullable<double> BonoAsistencia { get; set; }
        public Nullable<double> BonoProduccion { get; set; }
        public Nullable<double> Colacion { get; set; }
        public Nullable<double> Movilizacion { get; set; }
        public Nullable<double> BonoTurno { get; set; }
        public string CentroNombre { get; set; }
        public Nullable<int> Centro_Codigo { get; set; }
        public string Afp_Nombre { get; set; }
        public string Isapre_Nombre { get; set; }
        public int Rut { get; set; }
        public string Dv { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public Nullable<int> Comuna_Codigo { get; set; }
        public string comuna_nombre { get; set; }
        public string Direccion { get; set; }
        public string TelFijo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> Documento_Id { get; set; }
        public string TelCelular { get; set; }
        public string TipoCuenta { get; set; }
        public string NumeroCuenta { get; set; }
        public Nullable<int> Id_Banco { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> Pais_Codigo { get; set; }
        public Nullable<int> Region_Codigo { get; set; }
        public Nullable<int> Provincia_Codigo { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Vigencia { get; set; }
        public string NombreBanco { get; set; }
        public string Cazadora { get; set; }
        public string SegundoParrafo { get; set; }
        public string Instalacion { get; set; }
        public Nullable<double> Anticipacion { get; set; }
    }
}
