//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MssBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DOC_Finiquitos
    {
        public int Documento_Id { get; set; }
        public int DocumentoTipo_Id { get; set; }
        public int Usuario_Id { get; set; }
        public int Personal_Id { get; set; }
        public bool PorVisar { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string RutaFinal { get; set; }
        public Nullable<int> Finiquito_Id { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> Articulo_Numero { get; set; }
        public string Comentario { get; set; }
        public Nullable<double> Vacaciones { get; set; }
        public Nullable<int> Comuna_Codigo { get; set; }
        public string Nombres { get; set; }
        public string ApellidoMaterno { get; set; }
        public string ApellidoPaterno { get; set; }
        public string Dv { get; set; }
        public Nullable<int> Rut { get; set; }
        public string comuna_nombre { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<double> MontoTotal { get; set; }
    }
}
