//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MssBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Documentos_Visar
    {
        public bool PorVisar { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NombreDocumento { get; set; }
        public int Personal_Id { get; set; }
        public Nullable<int> CentroCosto_Id { get; set; }
        public Nullable<int> EstructuraSueldo_Id { get; set; }
        public Nullable<int> Comuna_Id { get; set; }
        public Nullable<int> Isapre_Id { get; set; }
        public Nullable<int> Pais_Id { get; set; }
        public Nullable<int> Provincia_Id { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public string Afp_Nombre { get; set; }
        public int Rut { get; set; }
        public string Dv { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Estado { get; set; }
        public string CentroNombre { get; set; }
        public string Pais_Nombre { get; set; }
        public string provincia_nombre { get; set; }
        public string comuna_nombre { get; set; }
        public Nullable<int> Estructura_Codigo { get; set; }
        public string Descripcion { get; set; }
        public string region_nombre { get; set; }
        public string Isapre_Nombre { get; set; }
        public int Documento_Id { get; set; }
    }
}
