//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MssBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DOC_Historial
    {
        public int Documento_Id { get; set; }
        public int DocumentoTipo_Id { get; set; }
        public string NombreDocumento { get; set; }
        public int Personal_Id { get; set; }
        public bool PorVisar { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public int Rut { get; set; }
        public string Dv { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public int Contrato_Id { get; set; }
        public string TipoContrato { get; set; }
        public Nullable<System.DateTime> FechaDesdeContrato { get; set; }
        public Nullable<System.DateTime> FechaHastaContrato { get; set; }
        public Nullable<int> Centro_Codigo { get; set; }
        public string CentroNombre { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> Vigencia { get; set; }
        public Nullable<System.DateTime> FechaDesdeAnexo { get; set; }
        public Nullable<System.DateTime> FechaHastaAnexo { get; set; }
    }
}
