//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MssBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Logs
    {
        public int Rut { get; set; }
        public string Dv { get; set; }
        public string Accion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
    }
}
